spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: david
    password: 4137
    url: jdbc:postgresql://localhost:5432/socialmedia
  jpa:
    show-sql: true
jwt:
  lifetime: 10m
socialmedia:
  files:
    valid-extensions: [".jpg", ".JPG", ".jpeg", ".JPEG", ".jpe", ".JPE", ".png"]
    valid-mime-types: ["image/png", "image/jpeg"]
    path: /home/david/uploadFiles