CREATE TABLE users
(
    username VARCHAR(50) PRIMARY KEY NOT NULL,
    password VARCHAR(255)            NOT NULL,
    email    VARCHAR(255)            NOT NULL UNIQUE
);
CREATE TABLE files
(
    saved_file_name   UUID                        NOT NULL,
    uploader_username VARCHAR(50)                 NOT NULL,
    real_file_name    VARCHAR(255)                NOT NULL,
    file_extension    VARCHAR(255)                NOT NULL,
    mime_type         VARCHAR(255)                NOT NULL,
    loading_time      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_files PRIMARY KEY (saved_file_name),
    CONSTRAINT FK_FILES_ON_UPLOADER_USERNAME FOREIGN KEY (uploader_username) REFERENCES users (username)
);
CREATE TABLE messages
(
    message_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text              TEXT                                    NOT NULL,
    sender_username   VARCHAR(50)                             NOT NULL,
    receiver_username VARCHAR(50)                             NOT NULL,
    sending_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    read              BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (message_id),
    CONSTRAINT FK_MESSAGES_ON_RECEIVER_USERNAME FOREIGN KEY (receiver_username) REFERENCES users (username),
    CONSTRAINT FK_MESSAGES_ON_SENDER_USERNAME FOREIGN KEY (sender_username) REFERENCES users (username)
);
CREATE TABLE publications
(
    publication_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255)                            NOT NULL,
    text             TEXT                                    NOT NULL,
    author_username  VARCHAR(50)                             NOT NULL,
    publication_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_publications PRIMARY KEY (publication_id),
    CONSTRAINT FK_PUBLICATIONS_ON_AUTHOR_USERNAME FOREIGN KEY (author_username) REFERENCES users (username)
);

CREATE TABLE publications_files
(
    id BIGSERIAL PRIMARY KEY,
    file_id        UUID   NOT NULL,
    publication_id BIGINT NOT NULL,
    UNIQUE (file_id, publication_id),
    CONSTRAINT fk_pubfil_on_file FOREIGN KEY (file_id) REFERENCES files (saved_file_name),
    CONSTRAINT fk_pubfil_on_publication FOREIGN KEY (publication_id) REFERENCES publications (publication_id)
);